// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPHf5ebqXzTIb297ag_TKYCHhNR5ybmA',
    appId: '1:193365538369:web:8d004eabe8b1e2f6b6b8c0',
    messagingSenderId: '193365538369',
    projectId: 'reservas-396d3',
    authDomain: 'reservas-396d3.firebaseapp.com',
    databaseURL: 'https://reservas-396d3-default-rtdb.firebaseio.com',
    storageBucket: 'reservas-396d3.firebasestorage.app',
    measurementId: 'G-PXB9B7P7LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80NLdaZpVfTbMi6_Nj88CDVcfh959XUg',
    appId: '1:193365538369:android:8658f0016539b9d8b6b8c0',
    messagingSenderId: '193365538369',
    projectId: 'reservas-396d3',
    databaseURL: 'https://reservas-396d3-default-rtdb.firebaseio.com',
    storageBucket: 'reservas-396d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrj_JsoZSyz6u4_YJjiYi7dFjTBGivTek',
    appId: '1:193365538369:ios:57f1213865bde254b6b8c0',
    messagingSenderId: '193365538369',
    projectId: 'reservas-396d3',
    databaseURL: 'https://reservas-396d3-default-rtdb.firebaseio.com',
    storageBucket: 'reservas-396d3.firebasestorage.app',
    iosClientId: '193365538369-uccf10viujmtfqodmsrtvpueg4g1h9v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.reserva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrj_JsoZSyz6u4_YJjiYi7dFjTBGivTek',
    appId: '1:193365538369:ios:57f1213865bde254b6b8c0',
    messagingSenderId: '193365538369',
    projectId: 'reservas-396d3',
    databaseURL: 'https://reservas-396d3-default-rtdb.firebaseio.com',
    storageBucket: 'reservas-396d3.firebasestorage.app',
    iosClientId: '193365538369-uccf10viujmtfqodmsrtvpueg4g1h9v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.reserva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZPHf5ebqXzTIb297ag_TKYCHhNR5ybmA',
    appId: '1:193365538369:web:b19a2b897053f6aab6b8c0',
    messagingSenderId: '193365538369',
    projectId: 'reservas-396d3',
    authDomain: 'reservas-396d3.firebaseapp.com',
    databaseURL: 'https://reservas-396d3-default-rtdb.firebaseio.com',
    storageBucket: 'reservas-396d3.firebasestorage.app',
    measurementId: 'G-43E936MHFV',
  );

}